### ISSUE TITLE
Text in "Orthography" column

### ISSUE THREAD

**Issue by benbrecht** [mvzaanen/N-uu_conversion#1]
I saw there's a lot of different ways extra text is added in the column - a lot the times without brackets. I am looking through your code to understand it now. (I didn't know where to just post comments, so I just made an issue ;))

**Comment by mvzaanen** [comment]
I have tried to implement a way to identify Eastern and Western (in brackets) and separate these.  For the others, I give a warning. They will clean up the spreadsheet more, hopefully cleaning all of this up.
